/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package example

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {

    }
}
