/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import static org.asynchttpclient.Dsl.asyncHttpClient;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

import org.asynchttpclient.Response;

public class App {
    public static void main(String[] args) throws InterruptedException, ExecutionException {
        Future<Response> response = asyncHttpClient().prepareGet("http://httpbin.org/anything")
                .addHeader("Content-Type", "application/json").execute();

        System.out.println(response.get().getResponseBody());
    }
}
